"""add character_icon to user

Revision ID: 484cd69af4f4
Revises: d79dfb8c9cf1
Create Date: 2025-05-10 14:30:28.050183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484cd69af4f4'
down_revision = 'd79dfb8c9cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_icon', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('character_icon')

    # ### end Alembic commands ###
